version: 35
imports:
- projectPath: Templates
  revision: 0.0.4
jobs:
- name: Maven CI
  steps:
  - !UseTemplateStep
    name: maven build & deploy
    templateName: Tigase Server - Maven build & deploy
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  projectDependencies:
  - projectPath: tigase/_server/tigase-utils
    buildProvider: !LastFinishedBuild
      jobName: Maven CI
    artifacts: '**'
  - projectPath: tigase/_server/tigase-xmltools
    buildProvider: !LastFinishedBuild
      jobName: Maven CI
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
